# See the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      # Ignore Storybook updates since they should be applied all at once, not piecemeal.
      # TODO: Once GitHub supports grouped updates, group Storybook dependencies together.
      #       https://github.com/github/roadmap/issues/148
      - dependency-name: "storybook"
      - dependency-name: "@storybook/addon-essentials"
      - dependency-name: "@storybook/addon-interactions"
      - dependency-name: "@storybook/addon-links"
      - dependency-name: "@storybook/addon-viewport"
      - dependency-name: "@storybook/blocks"
      - dependency-name: "@storybook/svelte"
      - dependency-name: "@storybook/sveltekit"
      - dependency-name: "@storybook/theming"
    reviewers:
      - "la-ldaf/ad-hoc-engineers"
    commit-message:
      prefix: "npm"
    labels:
      - "dependencies"
      - "dependabot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    reviewers:
      - "la-ldaf/ad-hoc-engineers"
    commit-message:
      prefix: "github-actions"
    labels:
      - "dependencies"
      - "dependabot"
