services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run dev -- --host"
    environment:
      KV_URL: "redis://kv"
  kv:
    image: "redis:alpine"
    ports:
      - "6379:6379"
