import {
  CONTENTFUL_DEFAULT_ENVIRONMENT,
  VERCEL_ENV,
  VERCEL_GIT_REPO_OWNER,
  VERCEL_GIT_REPO_SLUG,
  VERCEL_GIT_COMMIT_SHA,
  VERCEL_GIT_PULL_REQUEST_ID,
} from "$env/static/private";

export const load = () => ({
  CONTENTFUL_DEFAULT_ENVIRONMENT,
  VERCEL_ENV,
  VERCEL_GIT_REPO_OWNER,
  VERCEL_GIT_REPO_SLUG,
  VERCEL_GIT_COMMIT_SHA,
  VERCEL_GIT_PULL_REQUEST_ID,
});
