name: "Linting and Unit Testing"

#  by default, runs when a PR activity type
#  is `opened`, `synchronize`, or `reopened`
# (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
on: pull_request

# Allow the coverage reporter to write comments on GitHub PRs
permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    # Create a GitHub Pages subpath for this PR
    env:
      PR_PATH: pull/${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install
        run: npm ci

      - name: Prettier & ESLint
        run: npm run lint

      - name: svelte-check (diagnostic checks for unused CSS, Svelte A11y hints, and JS/TS errors)
        run: npm run check

      - name: Unit tests
        run: npm run test:unit:coverage

      - name: Report code coverage
        # https://github.com/marketplace/actions/code-coverage-report
        # Use hash over version to support delete-old-comments:
        # https://github.com/romeovs/lcov-reporter-action/issues/47#issuecomment-1362606540
        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true

      - name: Set preview URL
        run: echo "BASE_URL=https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/${{ env.PR_PATH}}/" >> $GITHUB_ENV

      - name: Deploy to PR preview
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref != 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-coverage-reports
          publish_dir: ./coverage
          destination_dir: ${{ env.PR_PATH }}

      - name: Post comment
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "A coverage report of ${{ github.event.after }} is uploaded and can be seen here:\n\n ✨ ${{ env.BASE_URL }} ✨\n\nChanges may take a few minutes to propagate. The source is here: https://github.com/${{ github.repository }}/tree/gh-pages-coverage-reports/${{ env.PR_PATH }}/"
